// UI Component Library — barrel export
// Import from '@/components/ui' instead of individual file paths.
export { Button } from './Button';
export type { ButtonProps, ButtonVariant, ButtonSize } from './Button';
export { IconButton } from './IconButton';
export type { IconButtonProps, IconButtonVariant, IconButtonSize } from './IconButton';
export { Badge } from './Badge';
export type { BadgeProps, BadgeVariant, BadgeSize } from './Badge';
export { StatusBadge } from './StatusBadge';
export type { StatusBadgeProps, TransactionStatus } from './StatusBadge';
export { ConfirmDialog } from './ConfirmDialog';
export type { ConfirmDialogProps, ConfirmDialogVariant } from './ConfirmDialog';
export { PageHeader } from './PageHeader';
export type { PageHeaderProps } from './PageHeader';
export { Tabs } from './Tabs';
export type { TabsProps, Tab, TabsVariant } from './Tabs';
export { Textarea } from './Textarea';
export type { TextareaProps } from './Textarea';
export { MobileTable } from './MobileTable';
export type { MobileTableProps, MobileTableColumn } from './MobileTable';
export { Alert, AlertDescription } from './Alert';
export { BottomSheet } from './BottomSheet';
export type { BottomSheetProps } from './BottomSheet';
export { Card, CardHeader, CardTitle, CardContent } from './Card';
export type { CardProps, CardVariant } from './Card';
export { CurrencyBadge } from './CurrencyBadge';
export { DatePicker } from './DatePicker';
export { Dialog, DialogContent, DialogHeader, DialogTitle, DialogFooter, DialogDescription, } from './Dialog';
export { Modal, ModalContent, ModalHeader, ModalTitle, ModalFooter, ModalDescription } from './Modal';
export type { ModalProps } from './Modal';
export { Dropdown, DropdownItem } from './Dropdown';
export { EmptyState } from './EmptyState';
export type { EmptyStateProps } from './EmptyState';
export { ErrorState } from './ErrorState';
export { Fab } from './Fab';
export { FinancialMetricCard } from './FinancialMetricCard';
export { HeroKpiCard } from './HeroKpiCard';
export { Input } from './Input';
export type { InputProps } from './Input';
export { KpiCompactCard } from './KpiCompactCard';
export { Label } from './Label';
export { MoneyField } from './MoneyField';
export { MoneyText } from './MoneyText';
export type { MoneyTextProps, MoneySemantic, MoneyCurrency, MoneySize } from './MoneyText';
export { MonthlyRecapBanner } from './MonthlyRecapBanner';
export { NumberInput } from './NumberInput';
export { OfflineBanner } from './OfflineBanner';
export { RiskAlertCard } from './RiskAlertCard';
export { SearchableSelect } from './SearchableSelect';
export { Select } from './Select';
export type { SelectProps } from './Select';
export { Skeleton } from './Skeleton';
export { SkeletonList } from './SkeletonList';
export { SwipeableListItem } from './SwipeableListItem';
export { TagChips } from './TagChips';
export { TagInput } from './TagInput';
export { TransactionPreviewCard } from './TransactionPreviewCard';
export { SectionHeading } from './SectionHeading';
export type { SectionHeadingProps } from './SectionHeading';
export { ThemeToggle } from './ThemeToggle';
export { UnifiedTitle } from './UnifiedTitle';
